"""Call-graph closure slicer for the cli_app golden oracle.

Replaces the LLM ``_synthesise_oracle`` with a deterministic, byte-for-byte copy
of the real upstream aws-cli source for the task's service, shipped VERBATIM,
plus a tiny GENERATED bootstrap so it runs small.

Design (validated end-to-end against MinIO + the aws-cli v2.28.23 source):

  * The gold = the **static-import closure** of the real code reachable from a
    fixed set of roots — ``clidriver.py``, ``__init__.py``, ``__main__.py``, and
    a GENERATED minimal ``handlers.py``. For the ``s3`` service the roots also
    include the whole ``customizations/s3`` subpackage; for ``dynamodb`` (and
    other model-generated services) they do not — DDB has no customization
    module, its verbs are built at runtime from the botocore service model. The
    closure follows ``import`` / ``from ... import`` edges WITHIN the awscli
    tree, resolving the alias ``botocore.*`` -> ``awscli/botocore/*`` and
    ``s3transfer.*`` -> ``awscli/s3transfer/*`` (the same alias
    ``awscli/__init__.py``'s ``TopLevelImportAliasFinder`` installs at runtime),
    and STOPS at external pip packages (the pyproject deps) + stdlib.
  * The GENERATED ``handlers.py`` keeps the same ``awscli_initialize`` signature
    but registers ONLY the GLOBAL handlers (arg parsing, output, errors,
    pagination, skeleton, waiters, ...) plus the service-specific plugin needed
    by the task (s3 plugin for s3; nothing extra for dynamodb). It DROPS every
    OTHER service-specific customization (ec2/rds/ecr/emr/eks/...). Because the
    generated handlers never imports the dropped customizations, the closure
    never pulls them in — that is what keeps the slice small AND avoids the
    KeyError a service customization raises when its service data is pruned.
  * Every awscli file the closure reaches is emitted VERBATIM (byte-for-byte),
    plus the botocore service **data** the reached code loads at runtime — the
    service model dirs for the task (``s3`` + ``sts`` for s3; ``dynamodb`` +
    ``sts`` for dynamodb) and the top-level ``endpoints.json`` /
    ``partitions.json`` — plus awscli's own ``data/`` (``cli.json`` /
    ``metadata.json``). Service models for everything else are dropped.
  * ``submission/aws`` is the ONLY generated file: an executable ``#!/bin/sh``
    shim that bootstraps the slice INLINE (``python3 -c`` prepends
    ``/workspace/submission`` to ``sys.path``, sets ``argv[0]="aws"``,
    dispatches to ``awscli.clidriver.main``). There is NO ``submission/main.py``.
    NO ``_botocore_compat`` shim, NO exclude-list, NO pip botocore — botocore is
    VENDORED.
  * The gold patch is a ``\\n``-only new-file diff (NOT ``str.splitlines()``,
    which corrupts files with form-feed / U+2028). Every emitted file is
    asserted to reconstruct byte-identically; a provenance sha256 manifest of
    the verbatim files is returned.
"""

from __future__ import annotations

import ast
import hashlib
import json
import re
import shutil
from pathlib import Path

_TREE_TOPS = {"awscli", "botocore", "s3transfer"}

_SERVICE_DATA_DIRS: dict[str, tuple[str, ...]] = {
    "s3": ("s3", "sts"),
    "dynamodb": ("dynamodb",),
}

_DATA_TOP_FILES = ("endpoints.json", "partitions.json")

_SERVICE_ENDPOINTS_KEEP: dict[str, frozenset[str]] = {
    "s3": frozenset({"s3", "sts"}),
    "dynamodb": frozenset({"dynamodb"}),
}


_GENERATED_HANDLERS_S3 = '''\
# Copyright 2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""Builtin CLI extensions (minimal slice: global handlers + s3 only).

GENERATED by repo2rlenv's call-graph slicer to replace upstream
awscli/handlers.py for the `aws s3` task slice. Keeps the GLOBAL event handlers
(arg parsing, output, errors, pagination, skeleton, waiters, ...) and the s3
plugin; DROPS every service-specific customization (ec2/rds/ddb/codedeploy/
ecr/emr/eks/...). Dropping the service registrations keeps the import closure
small (their modules and pruned service data never load) and avoids the
KeyError a service customization raises when its service data is absent.
"""

from awscli.argprocess import ParamShorthandParser
from awscli.clidriver import no_pager_handler
from awscli.customizations.addexamples import add_examples
from awscli.customizations.argrename import register_arg_renames
from awscli.customizations.assumerole import register_assume_role_provider
from awscli.customizations.binaryformat import add_binary_formatter
from awscli.customizations.cliinput import register_cli_input_args
from awscli.customizations.ec2.addcount import register_count_events
from awscli.customizations.ec2.protocolarg import register_protocol_args
from awscli.customizations.generatecliskeleton import (
    register_generate_cli_skeleton,
)
from awscli.customizations.globalargs import register_parse_global_args
from awscli.customizations.iot_data import register_custom_endpoint_note
from awscli.customizations.paginate import register_pagination
from awscli.customizations.removals import register_removals
from awscli.customizations.s3.s3 import s3_plugin_initialize
from awscli.customizations.s3errormsg import register_s3_error_msg
from awscli.customizations.timestampformat import register_timestamp_format
from awscli.customizations.toplevelbool import register_bool_params
from awscli.customizations.waiters import register_add_waiters
from awscli.paramfile import register_uri_param_handler


def awscli_initialize(event_handlers):
    event_handlers.register('session-initialized', register_uri_param_handler)
    event_handlers.register('session-initialized', add_binary_formatter)
    event_handlers.register('session-initialized', no_pager_handler)
    param_shorthand = ParamShorthandParser()
    event_handlers.register('process-cli-arg', param_shorthand)
    # The s3 error message needs to be registered before the
    # generic error handler.
    register_s3_error_msg(event_handlers)
    event_handlers.register('doc-examples.*.*', add_examples)
    register_cli_input_args(event_handlers)
    register_count_events(event_handlers)
    register_parse_global_args(event_handlers)
    register_pagination(event_handlers)
    s3_plugin_initialize(event_handlers)
    register_removals(event_handlers)
    register_generate_cli_skeleton(event_handlers)
    register_assume_role_provider(event_handlers)
    register_add_waiters(event_handlers)
    register_arg_renames(event_handlers)
    register_bool_params(event_handlers)
    register_protocol_args(event_handlers)
    register_timestamp_format(event_handlers)
    register_custom_endpoint_note(event_handlers)
'''


_GENERATED_HANDLERS_DDB = '''\
# Copyright 2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""Builtin CLI extensions (minimal slice: global handlers only).

GENERATED by repo2rlenv's call-graph slicer to replace upstream
awscli/handlers.py for the `aws dynamodb` task slice. DynamoDB's verbs are
model-generated from the botocore service model; there is no ``customizations/
dynamodb`` module. Keeps the GLOBAL event handlers (arg parsing, output, errors,
pagination, skeleton, waiters, ...) and DROPS every service-specific
customization (s3/ec2/rds/codedeploy/ecr/emr/eks/...). Dropping the service
registrations keeps the import closure small and avoids the KeyError a service
customization raises when its service data is absent.
"""

from awscli.argprocess import ParamShorthandParser
from awscli.clidriver import no_pager_handler
from awscli.customizations.addexamples import add_examples
from awscli.customizations.argrename import register_arg_renames
from awscli.customizations.assumerole import register_assume_role_provider
from awscli.customizations.binaryformat import add_binary_formatter
from awscli.customizations.cliinput import register_cli_input_args
from awscli.customizations.generatecliskeleton import (
    register_generate_cli_skeleton,
)
from awscli.customizations.globalargs import register_parse_global_args
from awscli.customizations.iot_data import register_custom_endpoint_note
from awscli.customizations.paginate import register_pagination
from awscli.customizations.removals import register_removals
from awscli.customizations.timestampformat import register_timestamp_format
from awscli.customizations.toplevelbool import register_bool_params
from awscli.customizations.waiters import register_add_waiters
from awscli.paramfile import register_uri_param_handler


def awscli_initialize(event_handlers):
    event_handlers.register('session-initialized', register_uri_param_handler)
    event_handlers.register('session-initialized', add_binary_formatter)
    event_handlers.register('session-initialized', no_pager_handler)
    param_shorthand = ParamShorthandParser()
    event_handlers.register('process-cli-arg', param_shorthand)
    event_handlers.register('doc-examples.*.*', add_examples)
    register_cli_input_args(event_handlers)
    register_parse_global_args(event_handlers)
    register_pagination(event_handlers)
    register_removals(event_handlers)
    register_generate_cli_skeleton(event_handlers)
    register_assume_role_provider(event_handlers)
    register_add_waiters(event_handlers)
    register_arg_renames(event_handlers)
    register_bool_params(event_handlers)
    register_timestamp_format(event_handlers)
    register_custom_endpoint_note(event_handlers)
'''


_SERVICE_HANDLERS: dict[str, str] = {
    "s3": _GENERATED_HANDLERS_S3,
    "dynamodb": _GENERATED_HANDLERS_DDB,
}


# GENERATED replacement for upstream ``awscli/handlers_registry.py``.
# Upstream (post-2026-07-07 on the v2 branch) added a lazy-load registry of
# ~60 service customizations declared as ``('module.path', 'attr')`` tuples.
# ``plugin.py`` walks the whole registry at driver init and dynamically imports
# every entry. Our slice keeps only the customizations the static-import closure
# actually reaches, so any string-imported customization the registry references
# but our closure did NOT keep raises ModuleNotFoundError before the CLI can run.
# We ship an empty registry; the generated ``handlers.py`` above registers every
# handler the slice actually needs via direct imports, so an empty lazy registry
# is safe.
_GENERATED_HANDLERS_REGISTRY = '''\
"""GENERATED stub replacing upstream awscli/handlers_registry.py for the slice.

The slice registers every handler it needs via direct import in the generated
handlers.py; the string-imported lazy registry upstream ships is intentionally
empty here so absent customizations do not raise at driver init.
"""

from __future__ import annotations

import enum


class CommandTableOp(enum.Enum):
    ADD = 'add'
    REMOVE = 'remove'
    REPLACE = 'replace'


PLUGIN_REGISTRY: dict = {}
MAIN_COMMAND_TABLE_OPS: list = []
'''


_AWS_SHIM = (
    "#!/bin/sh\n"
    'exec python3 -c \'import sys; sys.argv[0]="aws"; '
    'sys.path.insert(0, "/workspace/submission"); '
    'from awscli.clidriver import main; sys.exit(main())\' "$@"\n'
)


_STUB_AWSCLI_HELP = '''\
"""GENERATED stub for slice: `aws <cmd> help` is not reachable in subprocess mode.

clidriver.py imports OperationHelpCommand / ProviderHelpCommand /
ServiceHelpCommand at module top; those references are attribute-lookups the
non-help code paths never reach. The stubs satisfy the imports without
pulling in help.py's downstream (clidocs, topictags, bcdoc/*, botocore/docs/*).
"""

from __future__ import annotations


class _StubHelpCommand:
    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, *args, **kwargs):
        raise RuntimeError(
            "help is unavailable in the sliced runtime"
        )


OperationHelpCommand = _StubHelpCommand
ProviderHelpCommand = _StubHelpCommand
ServiceHelpCommand = _StubHelpCommand
'''


_STUB_AWSCLI_AUTOPROMPT_INIT = '''\
"""GENERATED stub for slice: autoprompt package is not reachable in subprocess mode."""
'''


_STUB_AWSCLI_AUTOPROMPT_CORE = '''\
"""GENERATED stub for slice: AutoPromptDriver is instantiated only in interactive mode.

clidriver.py imports AutoPromptDriver inside functions that fire only when the
interactive auto-prompt is enabled (tty + --cli-auto-prompt). subprocess.run
invocations of `aws dynamodb <cmd>` never reach those code paths, so a no-op
class satisfies the import without pulling in the autocomplete subtree.
"""

from __future__ import annotations


class AutoPromptDriver:
    def __init__(self, *args, **kwargs):
        pass

    def resolve_mode(self, *args, **kwargs):
        return "off"

    def prompt_for_args(self, *args, **kwargs):
        raise RuntimeError(
            "autoprompt is unavailable in the sliced runtime"
        )

    def prompt_for_values(self, *args, **kwargs):
        raise RuntimeError(
            "autoprompt is unavailable in the sliced runtime"
        )
'''


_STUB_AWSCLI_AUTOPROMPT_EXCEPTIONS = '''\
"""GENERATED stub for slice: prompter exceptions used only in error-handler dispatch."""

from __future__ import annotations


class PrompterKeyboardInterrupt(KeyboardInterrupt):
    pass
'''


_STUB_AWSCLI_CLIDOCS = '''\
"""GENERATED stub for slice: OperationDocumentEventHandler is only used by help rendering.

customizations/commands.py imports OperationDocumentEventHandler and uses it inside
render_doc(), which fires only for `aws <cmd> help`. subprocess-mode invocations
never hit that path, so the stub satisfies the import as a no-op class.
"""

from __future__ import annotations


class _StubDocEventHandler:
    def __init__(self, *args, **kwargs):
        pass


OperationDocumentEventHandler = _StubDocEventHandler
ProviderDocumentEventHandler = _StubDocEventHandler
ServiceDocumentEventHandler = _StubDocEventHandler
TopicListerDocumentEventHandler = _StubDocEventHandler
TopicDocumentEventHandler = _StubDocEventHandler
'''


_STUB_AWSCLI_TOPICTAGS = '''\
"""GENERATED stub for slice: TopicTagDB is only used by help rendering."""

from __future__ import annotations


class TopicTagDB:
    def __init__(self, *args, **kwargs):
        pass
'''


_STUB_AWSCLI_BCDOC_INIT = '''\
"""GENERATED stub for slice: bcdoc package is only reached via help rendering."""
'''


_STUB_AWSCLI_BCDOC_DOCEVENTS = '''\
"""GENERATED stub for slice: docevents.generate_events fires only under help rendering."""

from __future__ import annotations


DOC_EVENTS: dict[str, tuple[str, ...]] = {}


def generate_events(*args, **kwargs):
    return None
'''


_STUB_BOTOCORE_DOCS_DOCSTRING = '''\
"""GENERATED stub for slice: docstrings are only realized in help rendering.

botocore.client / botocore.waiter / botocore.docs.paginator import these classes
to assign as __doc__ on dynamically generated client methods. The originals are
str subclasses that lazily render RST-formatted help text; the stubs preserve
the str-subclass contract (so ``__doc__ = X()`` works) but render an empty
string in the sliced runtime where help is never surfaced.
"""

from __future__ import annotations


class LazyLoadedDocstring(str):
    def __new__(cls, *args, **kwargs):
        return str.__new__(cls, "")

    def __init__(self, *args, **kwargs):
        pass


class ClientMethodDocstring(LazyLoadedDocstring):
    pass


class WaiterDocstring(LazyLoadedDocstring):
    pass


class PaginatorDocstring(LazyLoadedDocstring):
    pass
'''


_STUB_BOTOCORE_DOCS_UTILS = '''\
"""GENERATED stub for slice: docs.utils classes are registered as `docs.*` handlers.

botocore.handlers registers instances of AutoPopulatedParam / AppendParamDocumentation
/ HideParamFromOperations against ``docs.*`` events. Those events fire only during
help rendering, which the sliced runtime never triggers. The stubs preserve the
constructor signature and method surface (via ``_NoOp``) so import-time handler
registration succeeds; the callbacks are never invoked in subprocess mode.
"""

from __future__ import annotations


class _NoOp:
    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, *args, **kwargs):
        return None

    def __getattr__(self, name):
        return _NoOp()


class AutoPopulatedParam(_NoOp):
    def __init__(self, name=None, *args, **kwargs):
        self.name = name


class AppendParamDocumentation(_NoOp):
    pass


class HideParamFromOperations(_NoOp):
    pass
'''


_STUB_BOTOCORE_DOCS_INIT = '''\
"""GENERATED stub for slice: botocore.docs facade is unused in subprocess mode."""
'''


def _project_endpoints_json(text: str, keep_services: frozenset[str]) -> str:
    """Filter endpoints.json's ``partitions[].services`` map to keep only listed services.

    The endpoints.json v3 schema has a top-level ``partitions`` list; each entry
    has a ``services`` dict keyed by service name (``s3``, ``dynamodb``, ...).
    We drop every service not in ``keep_services`` while preserving the outer
    structure (partition metadata, regions, defaults) — botocore's endpoint
    resolver stays functional for kept services and never touches removed ones.
    """
    data = json.loads(text)
    partitions = data.get("partitions") or []
    for partition in partitions:
        services = partition.get("services")
        if isinstance(services, dict):
            partition["services"] = {
                name: cfg for name, cfg in services.items() if name in keep_services
            }
    return json.dumps(data, indent=2, separators=(",", ": "))


def _project_partitions_json(text: str, keep_services: frozenset[str]) -> str:
    """Filter partitions.json.

    partitions.json is a small (~267 lines) file mirroring the newer endpoints.json
    v3 schema. We apply the same ``services`` projection defensively; if the file
    schema does not contain per-service data, the unchanged serialization is
    returned.
    """
    data = json.loads(text)
    partitions = data.get("partitions") or []
    changed = False
    for partition in partitions:
        services = partition.get("services")
        if isinstance(services, dict):
            partition["services"] = {
                name: cfg for name, cfg in services.items() if name in keep_services
            }
            changed = True
    if not changed:
        return text
    return json.dumps(data, indent=2, separators=(",", ": "))


_DATA_TOP_PROJECTORS = {
    "endpoints.json": _project_endpoints_json,
    "partitions.json": _project_partitions_json,
}


class SliceError(RuntimeError):
    """Raised when the upstream source cannot be sliced byte-identically."""


def _pkg_parts_for(awscli_root: Path, path: Path) -> list[str]:
    rel = path.relative_to(awscli_root)
    parts = ["awscli", *rel.parts]
    return parts[:-1]


def _module_to_paths(awscli_root: Path, mod: str) -> list[Path]:
    parts = mod.split(".")
    if parts[0] == "awscli":
        parts = parts[1:]
        if not parts:
            init = awscli_root / "__init__.py"
            return [init] if init.is_file() else []
    rel = awscli_root / Path(*parts)
    results: list[Path] = []
    pyfile = rel.with_suffix(".py")
    initfile = rel / "__init__.py"
    if pyfile.is_file():
        results.append(pyfile)
    if initfile.is_file():
        results.append(initfile)
    return results


def _imports_from_source(src: str, pkg_parts: list[str]) -> set[str]:
    out: set[str] = set()
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return out
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                out.add(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0:
                if node.module:
                    out.add(node.module)
                    for alias in node.names:
                        out.add(f"{node.module}.{alias.name}")
            else:
                anchor = pkg_parts[: len(pkg_parts) - (node.level - 1)]
                if node.module:
                    base = ".".join(anchor + node.module.split("."))
                    out.add(base)
                    for alias in node.names:
                        out.add(f"{base}.{alias.name}")
                else:
                    for alias in node.names:
                        out.add(".".join([*anchor, alias.name]))
    return out


# ---------------------------------------------------------------------------
# S3 per-subset manifest reassembly
# ---------------------------------------------------------------------------
# The whole `aws s3` command family (mb/rb/cp/ls/mv/rm/sync) is defined in ONE
# module, ``customizations/s3/subcommands.py``, which EAGERLY imports the
# transfer/sync engine. So an import-closure that keeps that file whole is
# command-subset-INDEPENDENT: every task pulls the full engine. To make the
# golden patch per-task we reassemble subcommands.py + s3.py to the task's
# command subset (verbatim subset of upstream classes/imports/registrations).
# A bucket/list-only subset (e.g. ls+mb) thus drops the transfer engine; any
# subset containing cp/mv/rm/sync (or rb via --force -> rm) keeps it.
# botocore stays whole either way.
#
# DynamoDB has NO analogous customization module — its verbs are built at
# runtime from the botocore service model — so this code path only applies to
# service="s3".

_CMD_TO_CLASS = {
    "ls": "ListCommand",
    "cp": "CpCommand",
    "mv": "MvCommand",
    "rm": "RmCommand",
    "sync": "SyncCommand",
    "mb": "MbCommand",
    "rb": "RbCommand",
}
_S3_SHARED_CLASSES = frozenset({"S3Command", "CommandParameters"})


def _raw_lines(src_lines: list[str], node: ast.AST) -> str:
    start = min([d.lineno for d in getattr(node, "decorator_list", [])] + [node.lineno])
    return "\n".join(src_lines[start - 1 : node.end_lineno])


def _import_bound_names(stmt: ast.AST) -> set[str]:
    names: set[str] = set()
    for a in getattr(stmt, "names", []):
        if isinstance(stmt, ast.Import):
            names.add((a.asname or a.name).split(".")[0])
        else:
            names.add(a.asname or a.name)
    return names


def _keep_command_classes(sub_src: str, commands: list[str]) -> tuple[set[str], dict]:
    tree = ast.parse(sub_src)
    classes = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    keep = set(_S3_SHARED_CLASSES) | {_CMD_TO_CLASS[c] for c in commands if c in _CMD_TO_CLASS}
    keep &= set(classes)
    changed = True
    while changed:
        changed = False
        refs: set[str] = set()
        for name in list(keep):
            for sub in ast.walk(classes[name]):
                if isinstance(sub, ast.Name):
                    refs.add(sub.id)
        for cand in classes:
            if cand not in keep and cand in refs:
                keep.add(cand)
                changed = True
    return keep, classes


def _reassemble_subcommands(sub_src: str, commands: list[str]) -> str:
    keep, classes = _keep_command_classes(sub_src, commands)
    lines = sub_src.split("\n")
    tree = ast.parse(sub_src)
    kept_nodes: list[ast.AST] = [classes[n] for n in keep]
    kept_nodes += [
        s for s in tree.body if not isinstance(s, (ast.Import, ast.ImportFrom, ast.ClassDef))
    ]
    refs: set[str] = set()
    for n in kept_nodes:
        for sub in ast.walk(n):
            if isinstance(sub, ast.Name):
                refs.add(sub.id)
            elif isinstance(sub, ast.Attribute):
                refs.add(sub.attr)
    parts: list[str] = []
    for stmt in tree.body:
        if isinstance(stmt, ast.ClassDef):
            if stmt.name in keep:
                parts.append(_raw_lines(lines, stmt))
        elif isinstance(stmt, (ast.Import, ast.ImportFrom)):
            if _import_bound_names(stmt) & refs:
                parts.append(_raw_lines(lines, stmt))
        else:
            parts.append(_raw_lines(lines, stmt))
    return "\n\n".join(parts) + "\n"


def _reassemble_s3py(s3_src: str, keep_cmd_classes: set[str], drop_sync_reg: bool) -> str:
    lines = s3_src.split("\n")
    tree = ast.parse(s3_src)
    drop: set[int] = set()
    replace: dict[int, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            mod = node.module or ""
            if mod.endswith("s3.subcommands"):
                kept = [a.name for a in node.names if a.name in keep_cmd_classes]
                replace[node.lineno] = (
                    "from awscli.customizations.s3.subcommands import " + ", ".join(kept)
                )
                for ln in range(node.lineno + 1, (node.end_lineno or node.lineno) + 1):
                    drop.add(ln)
            elif drop_sync_reg and "syncstrategy" in mod:
                for ln in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                    drop.add(ln)
        elif isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "SUBCOMMANDS" for t in node.targets
        ):
            for elt in node.value.elts:
                cls = None
                for k, v in zip(elt.keys, elt.values, strict=False):
                    if isinstance(k, ast.Constant) and k.value == "command_class":
                        cls = getattr(v, "id", None)
                if cls not in keep_cmd_classes:
                    for ln in range(elt.lineno, (elt.end_lineno or elt.lineno) + 1):
                        drop.add(ln)
        elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
            if drop_sync_reg and "register_sync_strategies" in {
                n.id for n in ast.walk(node) if isinstance(n, ast.Name)
            }:
                for ln in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                    drop.add(ln)
    return "\n".join(replace.get(i, ln) for i, ln in enumerate(lines, 1) if i not in drop)


def _reassemble_manifests(awscli_root: Path, commands: list[str]) -> dict[Path, str]:
    sub_path = awscli_root / "customizations" / "s3" / "subcommands.py"
    s3_path = awscli_root / "customizations" / "s3" / "s3.py"
    sub_src = sub_path.read_text(encoding="utf-8")
    s3_src = s3_path.read_text(encoding="utf-8")
    keep_cmd = {_CMD_TO_CLASS[c] for c in commands if c in _CMD_TO_CLASS}
    overrides = {
        sub_path: _reassemble_subcommands(sub_src, commands),
        s3_path: _reassemble_s3py(s3_src, keep_cmd, drop_sync_reg="sync" not in commands),
    }
    for p, txt in overrides.items():
        try:
            ast.parse(txt)
        except SyntaxError as exc:
            raise SliceError(f"reassembled {p.name} does not parse: {exc}") from exc
    return overrides


def _verb_to_operation(verb: str) -> str:
    return "".join(p.capitalize() for p in verb.split("-"))


def _closure_shapes(shapes: dict, roots: set[str]) -> set[str]:
    """BFS shape reachability walk. Handles structure.members[*].shape,
    list.member.shape, map.{key,value}.shape."""
    reached, queue = set(), list(roots)
    while queue:
        name = queue.pop()
        if name in reached:
            continue
        reached.add(name)
        if name not in shapes:
            continue
        s = shapes[name]
        t = s.get("type")
        if t == "structure":
            for m in s.get("members", {}).values():
                if "shape" in m:
                    queue.append(m["shape"])
        elif t == "list":
            m = s.get("member", {})
            if "shape" in m:
                queue.append(m["shape"])
        elif t == "map":
            for k in ("key", "value"):
                m = s.get(k, {})
                if "shape" in m:
                    queue.append(m["shape"])
    return reached


def _assert_ddb_slice_closed(operations: dict, shapes: dict) -> None:
    for op_name, op in operations.items():
        refs = set()
        for src in ("input", "output"):
            sh = op.get(src, {}).get("shape")
            if sh:
                refs.add(sh)
        for err in op.get("errors", []):
            sh = err.get("shape")
            if sh:
                refs.add(sh)
        closure = _closure_shapes(shapes, refs)
        missing = closure - set(shapes)
        if missing:
            raise SliceError(
                f"DDB slice closure incomplete: op {op_name!r} references "
                f"shapes not in pruned dict: {sorted(missing)}"
            )


def _slice_dynamodb_data(awscli_root: Path, verbs: list[str]) -> dict[Path, str]:
    """Prune DDB service-2.json + paginators-1.json + waiters-2.json to kept verbs.

    Returns {absolute Path: pruned utf-8 text}. Endpoint-* files are NOT
    included; they pass through _carry byte-identically. Pruned JSON is
    semantic-identity only (json.loads/dumps round-trip loses whitespace);
    caller records original sha256 in provenance.
    """
    ddb_dir = awscli_root / "botocore" / "data" / "dynamodb" / "2012-08-10"
    if not ddb_dir.is_dir():
        raise SliceError(f"no DDB data dir at {ddb_dir}")

    keep_ops = {_verb_to_operation(v) for v in verbs}

    service_path = ddb_dir / "service-2.json"
    model = json.loads(service_path.read_text(encoding="utf-8"))
    all_ops = model.get("operations", {})
    unknown = keep_ops - set(all_ops)
    if unknown:
        raise SliceError(
            f"DDB slice: unknown ops {sorted(unknown)}; available: {sorted(all_ops)[:20]}..."
        )
    pruned_ops = {k: all_ops[k] for k in sorted(keep_ops)}

    all_shapes = model.get("shapes", {})
    roots = set()
    for op in pruned_ops.values():
        for src in ("input", "output"):
            sh = op.get(src, {}).get("shape")
            if sh:
                roots.add(sh)
        for err in op.get("errors", []):
            sh = err.get("shape")
            if sh:
                roots.add(sh)
    reached = _closure_shapes(all_shapes, roots)
    pruned_shapes = {name: all_shapes[name] for name in sorted(reached) if name in all_shapes}

    _assert_ddb_slice_closed(pruned_ops, pruned_shapes)

    pruned_model = {
        "version": model.get("version"),
        "metadata": model.get("metadata", {}),
        "operations": pruned_ops,
        "shapes": pruned_shapes,
    }
    if "documentation" in model:
        pruned_model["documentation"] = model["documentation"]

    overrides = {service_path: json.dumps(pruned_model, indent=2, separators=(",", ": "))}

    paginators_path = ddb_dir / "paginators-1.json"
    if paginators_path.is_file():
        pag = json.loads(paginators_path.read_text(encoding="utf-8"))
        pag_ops = pag.get("pagination", {})
        pruned_pag = {op: pag_ops[op] for op in sorted(pag_ops) if op in keep_ops}
        overrides[paginators_path] = json.dumps(
            {"pagination": pruned_pag}, indent=2, separators=(",", ": ")
        )

    waiters_path = ddb_dir / "waiters-2.json"
    if waiters_path.is_file():
        wait = json.loads(waiters_path.read_text(encoding="utf-8"))
        waiters = wait.get("waiters", {})
        pruned_waiters = {name: w for name, w in waiters.items() if w.get("operation") in keep_ops}
        overrides[waiters_path] = json.dumps(
            {"version": wait.get("version"), "waiters": pruned_waiters},
            indent=2,
            separators=(",", ": "),
        )

    return overrides


def _compute_closure(
    awscli_root: Path,
    *,
    service: str,
    overrides: dict[Path, str] | None = None,
) -> set[Path]:
    """BFS static-import closure. For ``service='s3'`` the whole
    ``customizations/s3`` subpackage is anchored (or, if ``overrides`` is
    supplied, the reassembled manifests are anchored so the pruned engine
    imports fall out). For ``service='dynamodb'`` no customization subpackage is
    anchored — DDB's verbs are built at runtime from the botocore service model,
    so the closure comes solely from clidriver/__init__/__main__ + the generated
    DDB handlers."""
    overrides = overrides or {}
    closure: set[Path] = set()
    worklist: list[tuple[str, list[str]]] = []
    handlers_src = _SERVICE_HANDLERS[service]

    def _read(path: Path) -> str:
        ov = overrides.get(path)
        return ov if ov is not None else path.read_text(encoding="utf-8")

    def _seed(src: str, pkg: list[str]) -> None:
        for mod in _imports_from_source(src, pkg):
            worklist.append((mod, pkg))

    for rel in ("clidriver.py", "__init__.py", "__main__.py"):
        p = awscli_root / rel
        if p.is_file():
            closure.add(p)
            _seed(_read(p), _pkg_parts_for(awscli_root, p))

    handlers_path = awscli_root / "handlers.py"
    closure.add(handlers_path)
    _seed(handlers_src, ["awscli"])

    if service == "s3":
        if overrides:
            for p in overrides:
                if p.is_file():
                    closure.add(p)
                    _seed(_read(p), _pkg_parts_for(awscli_root, p))
        else:
            for p in (awscli_root / "customizations" / "s3").rglob("*.py"):
                if p.is_file():
                    closure.add(p)
                    _seed(_read(p), _pkg_parts_for(awscli_root, p))

    seen_modules: set[str] = set()
    while worklist:
        mod, pkg = worklist.pop()
        if mod in seen_modules:
            continue
        seen_modules.add(mod)
        if mod.split(".")[0] not in _TREE_TOPS:
            continue
        # Importing `a.b.c` runs the parent package __init__.py files (`a`, `a.b`),
        # which may themselves import submodules (e.g. botocore/docs/__init__.py does
        # `from botocore.docs.service import ...`). Ancestor packages must therefore
        # be enqueued so their own imports are followed.
        parts = mod.split(".")
        for i in range(1, len(parts)):
            anc = ".".join(parts[:i])
            if anc not in seen_modules:
                worklist.append((anc, pkg))
        for fpath in _module_to_paths(awscli_root, mod):
            if fpath in closure:
                continue
            closure.add(fpath)
            _seed(_read(fpath), _pkg_parts_for(awscli_root, fpath))
    return closure


def _parse_pyproject_externals(source_root: Path) -> list[str]:
    """Parse ``[project].dependencies`` from the cloned repo's pyproject.toml.

    These are the EXTERNAL pip deps the golden image installs (colorama,
    docutils, ruamel.yaml(.clib), prompt-toolkit, distro, awscrt,
    python-dateutil, jmespath, urllib3, ...) — NOT botocore/boto3/s3transfer,
    which are vendored in the slice.
    """
    pp = source_root / "pyproject.toml"
    if not pp.is_file():
        raise SliceError(f"no pyproject.toml under source_root: {source_root}")
    raw = pp.read_text(encoding="utf-8")
    try:
        import tomllib

        data = tomllib.loads(raw)
        deps = data.get("project", {}).get("dependencies")
        if isinstance(deps, list) and all(isinstance(d, str) for d in deps):
            return [d.strip() for d in deps if d.strip()]
    except Exception:
        pass
    m = re.search(r"(?ms)^\s*dependencies\s*=\s*\[(.*?)\]", raw)
    if not m:
        raise SliceError("could not locate [project].dependencies in pyproject.toml")
    body = m.group(1)
    body = re.sub(r"#.*", "", body)
    out: list[str] = []
    for tok in re.findall(r'"([^"]+)"|\'([^\']+)\'', body):
        spec = tok[0] or tok[1]
        if spec.strip():
            out.append(spec.strip())
    if not out:
        raise SliceError("[project].dependencies parsed empty")
    return out


def _newfile_diff(files: dict[str, str], exec_paths: frozenset[str] = frozenset()) -> str:
    """``git apply``-compatible all-new-file diff, splitting ONLY on ``\\n``.

    Unlike ``str.splitlines()`` (which silently corrupts files containing
    form-feed / U+2028 / vertical-tab), this splits on ``\\n`` exactly as git
    does, so applied bytes equal source bytes. Paths sorted for determinism.
    Paths in ``exec_paths`` are emitted with mode ``100755`` so the
    language-agnostic ``aws`` entry shim is executable after ``git apply``.
    """
    out: list[str] = []
    for path in sorted(files):
        mode = "100755" if path in exec_paths else "100644"
        content = files[path]
        if content == "":
            out.append(
                f"diff --git a/{path} b/{path}\nnew file mode {mode}\nindex 0000000..e69de29\n"
            )
            continue
        trailing_nl = content.endswith("\n")
        lines = content.split("\n")
        if trailing_nl:
            lines = lines[:-1]
        n = len(lines)
        out.append(
            f"diff --git a/{path} b/{path}\n"
            f"new file mode {mode}\n"
            "index 0000000..0000001\n"
            "--- /dev/null\n"
            f"+++ b/{path}\n"
            f"@@ -0,0 +1,{n} @@\n"
        )
        out.append("".join(f"+{ln}\n" for ln in lines))
        if not trailing_nl and content:
            out.append("\\ No newline at end of file\n")
    return "".join(out)


def _assert_diff_roundtrip(gold_files: dict[str, str]) -> None:
    for path, content in gold_files.items():
        trailing_nl = content.endswith("\n")
        lines = content.split("\n")
        if trailing_nl:
            lines = lines[:-1]
        recon = "\n".join(lines) + ("\n" if trailing_nl else "")
        if recon != content:
            raise SliceError(f"diff round-trip would corrupt {path}")


def _assert_subset_verbatim(reassembled: str, original: str, name: str) -> None:
    """Every non-blank line of a reassembled manifest must be byte-identical
    with a line of the upstream file — i.e. nothing was synthesized, only
    classes/imports were excised. The single allowed exception is s3.py's
    rewritten subcommands import, which lists a subset of the real upstream
    symbols."""
    orig_lines = set(original.split("\n"))
    for ln in reassembled.split("\n"):
        s = ln.strip()
        if not s:
            continue
        if ln in orig_lines:
            continue
        if s.startswith("from awscli.customizations.s3.subcommands import "):
            continue
        raise SliceError(f"reassembled {name} introduced a non-upstream line: {ln!r}")


def build_slice_gold(
    source_root: Path,
    commands: list[str] | None = None,
    *,
    service: str = "s3",
) -> tuple[dict[str, str], str, dict[str, str], list[str]]:
    """Slice the cloned aws-cli source into a byte-identical golden submission.

    ``service`` picks which family of subcommands the slice targets:

      * ``"s3"`` — the customization-driven family (mb/rb/cp/ls/mv/rm/sync).
        When ``commands`` is given, the two s3 manifest files are reassembled
        to that subset so the transfer/sync engine files the subset never
        reaches drop out of the closure. When ``commands`` is None the legacy
        whole-s3-package slice is produced.
      * ``"dynamodb"`` — model-generated verbs (create-table, put-item, ...).
        There is no customization module, so ``commands`` is ignored for the
        purpose of slice scoping: every DDB task ships the same slice
        (clidriver + closure + botocore + ``data/dynamodb`` + ``data/sts``).

    Returns ``(gold_files, gold_diff, provenance, externals)``:
      * ``gold_files`` — {submission-relative path -> text content} for every
        file the gold patch creates.
      * ``gold_diff`` — the ``git apply``-ready multi-file patch (\\n-safe).
      * ``provenance`` — {``awscli/<rel>`` -> sha256} for every VERBATIM awscli
        file (byte-identity audit trail). The generated handlers + reassembled
        manifests are NOT in provenance (they are generated / verbatim-subset).
      * ``externals`` — the ``[project].dependencies`` parsed from the cloned
        repo's pyproject.toml.

    Raises ``SliceError`` if the source is not aws-cli v2 or any file cannot be
    carried byte-identically through the patch.
    """
    if service not in _SERVICE_HANDLERS:
        raise SliceError(f"unsupported service: {service!r} (known: {sorted(_SERVICE_HANDLERS)})")
    root = Path(source_root)
    awscli = root / "awscli"
    if not awscli.is_dir():
        raise SliceError(f"no awscli/ under source_root: {root}")
    if not (awscli / "clidriver.py").is_file() or not (awscli / "__init__.py").is_file():
        raise SliceError(f"{awscli} is not an aws-cli source tree (missing clidriver/__init__)")

    externals = _parse_pyproject_externals(root)

    overrides: dict[Path, str] | None = None
    stub_paths: set[Path] = set()
    if service == "s3" and commands:
        overrides = _reassemble_manifests(awscli, commands)
    elif service == "dynamodb" and commands:
        overrides = _slice_dynamodb_data(awscli, commands)

    if service == "dynamodb":
        stubs = {
            awscli / "help.py": _STUB_AWSCLI_HELP,
            awscli / "clidocs.py": _STUB_AWSCLI_CLIDOCS,
            awscli / "topictags.py": _STUB_AWSCLI_TOPICTAGS,
            awscli / "autoprompt" / "__init__.py": _STUB_AWSCLI_AUTOPROMPT_INIT,
            awscli / "autoprompt" / "core.py": _STUB_AWSCLI_AUTOPROMPT_CORE,
            awscli / "autoprompt" / "exceptions.py": _STUB_AWSCLI_AUTOPROMPT_EXCEPTIONS,
            awscli / "bcdoc" / "__init__.py": _STUB_AWSCLI_BCDOC_INIT,
            awscli / "bcdoc" / "docevents.py": _STUB_AWSCLI_BCDOC_DOCEVENTS,
            awscli / "botocore" / "docs" / "__init__.py": _STUB_BOTOCORE_DOCS_INIT,
            awscli / "botocore" / "docs" / "docstring.py": _STUB_BOTOCORE_DOCS_DOCSTRING,
            awscli / "botocore" / "docs" / "utils.py": _STUB_BOTOCORE_DOCS_UTILS,
        }
        stub_paths = set(stubs)
        if overrides is None:
            overrides = dict(stubs)
        else:
            overrides.update(stubs)

    closure = _compute_closure(awscli, service=service, overrides=overrides)
    handlers_path = awscli / "handlers.py"
    handlers_registry_path = awscli / "handlers_registry.py"
    handlers_src = _SERVICE_HANDLERS[service]
    data_keep_dirs = _SERVICE_DATA_DIRS[service]

    gold_files: dict[str, str] = {}
    provenance: dict[str, str] = {}

    def _carry(rel_posix: str, src_path: Path) -> None:
        raw = src_path.read_bytes()
        provenance[f"awscli/{rel_posix}"] = hashlib.sha256(raw).hexdigest()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise SliceError(
                f"non-utf8 file cannot be carried in a text patch: {rel_posix}: {exc}"
            ) from exc
        if text.encode("utf-8") != raw:
            raise SliceError(f"utf-8 round-trip changed bytes: {rel_posix}")
        gold_files[f"submission/awscli/{rel_posix}"] = text

    ov = overrides or {}
    for src_path in sorted(closure):
        if "__pycache__" in src_path.parts or src_path.suffix == ".pyc":
            continue
        rel = src_path.relative_to(awscli).as_posix()
        if src_path == handlers_path:
            gold_files["submission/awscli/handlers.py"] = handlers_src
            continue
        if src_path == handlers_registry_path:
            gold_files["submission/awscli/handlers_registry.py"] = _GENERATED_HANDLERS_REGISTRY
            continue
        if src_path in ov:
            if src_path not in stub_paths:
                _assert_subset_verbatim(ov[src_path], src_path.read_text(encoding="utf-8"), rel)
            gold_files[f"submission/awscli/{rel}"] = ov[src_path]
            continue
        _carry(rel, src_path)

    if service == "s3" and not any(
        k.endswith("/awscli/customizations/s3/subcommands.py") for k in gold_files
    ):
        raise SliceError(
            "closure is missing customizations/s3/subcommands.py — not a usable s3 gold"
        )

    for p in sorted((awscli / "data").rglob("*")):
        if p.is_file() and "__pycache__" not in p.parts:
            _carry(p.relative_to(awscli).as_posix(), p)

    bdata = awscli / "botocore" / "data"
    for d in data_keep_dirs:
        dpath = bdata / d
        if dpath.is_dir():
            for p in sorted(dpath.rglob("*")):
                if p.is_file() and "__pycache__" not in p.parts:
                    rel = p.relative_to(awscli).as_posix()
                    if p in ov:
                        provenance[f"awscli/{rel}"] = hashlib.sha256(p.read_bytes()).hexdigest()
                        gold_files[f"submission/awscli/{rel}"] = ov[p]
                    else:
                        _carry(rel, p)
    keep_services = _SERVICE_ENDPOINTS_KEEP.get(service, frozenset())
    for j in _DATA_TOP_FILES:
        jp = bdata / j
        if not jp.is_file():
            continue
        rel = jp.relative_to(awscli).as_posix()
        projector = _DATA_TOP_PROJECTORS.get(j)
        if projector is None or not keep_services:
            _carry(rel, jp)
            continue
        raw = jp.read_bytes()
        provenance[f"awscli/{rel}"] = hashlib.sha256(raw).hexdigest()
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise SliceError(f"non-utf8 data file cannot be projected: {rel}: {exc}") from exc
        gold_files[f"submission/awscli/{rel}"] = projector(text, keep_services)

    gold_files["submission/aws"] = _AWS_SHIM

    gold_diff = _newfile_diff(gold_files, exec_paths=frozenset({"submission/aws"}))

    _assert_diff_roundtrip(gold_files)

    return gold_files, gold_diff, provenance, externals


def materialize_slice(
    source_root: Path,
    dest_root: Path,
    commands: list[str] | None = None,
    *,
    service: str = "s3",
) -> dict[str, str]:
    """Write the slice directly to ``dest_root`` (a runnable submission tree),
    bypassing the diff. Used for local validation."""
    gold_files, _diff, provenance, _externals = build_slice_gold(
        source_root, commands, service=service
    )
    dest = Path(dest_root)
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    for rel, content in gold_files.items():
        sub = rel.split("/", 1)[1] if rel.startswith("submission/") else rel
        target = dest / sub
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return provenance
